### PR TITLE
Return stable references from useMiniSearch() hook

### PR DESCRIPTION
**Pull request by Neezurft**
Hello there,

I've been using this library on a project I maintain and I really like it! kudos.

After having using it for a while, I realised that it was easy to get into some unexpected behaviour so as part of this MR I added another set of tests to reproduce some of the issues I encountered and also added a fix.

Let me know what you think, I'm happy to elaborate on the rationale more if you want me to.

### CODE REVIEW

**Comment by lucaong** [comment]
Hi @Neezurft , thanks a lot! I’ll review this soon

**Comment by mrienstra** [comment]
🎃 @lucaong, friendly reminder, review when you have time. 🍬

**Comment by lucaong** [comment]
Thanks a lot @Neezurft  for the PR and @mrienstra for the reminder! Sorry it took so long. I am merging this now and will soon release it as `v6.0.2`.

**Comment by lucaong** [comment]
Released as `v6.0.2`

**Pull request merged**
